name: Terraform-AWS

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: HashiCorp Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      
      - name: GPG Config
        run:  wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      
      - name: "hashicorp archive keyring.gpg"  
        run:  echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      
      - name: "apt update & install terraform"  
        run:  sudo apt update && sudo apt install terraform
      
      - name: Executar comandos Terraform
        run: |
          comandos=(
          "terraform init"
          "terraform providers"
          "terraform refresh"
          "terraform plan"
          "terraform validate"
            )

          for comando in "${comandos[@]}"
          do
          
          echo "Executando o comando: $comando"
          $comando

          done

          lista=()
          for i in "${comandos[@]}"
          do
          lista+=("$i ; ");
          sleep 1;
          done
          echo "Comandos executados: ${lista[@]}"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Refresh
        run: terraform refresh
      
      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform validate
        run: terraform validate
      
      - name: Complete
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: for i in $(seq 1 1 10); do echo $i; sleep 1; done
